export const FORCE_DUMMY_APIS = [
    // 'user/login',
    // 'user/profile',

    // 'canhan/timKiemLichSu',
    // 'canhan/danhSachLichSu',
    'ds_bao_cao_tong_hop_kinh_te',
    'ds_bao_cao_tong_hop_giao_duc',
    'loai_hinh_bao_cao',
    // 'tinKhanCap/getListEmergency',
    // 'tinKhanCap/getEmergencyDetail',
    // 'ds_nhiem_vu',
    // 'nhiem_vu_chi_tiet',
    // 'nhiem_vu/giao/by_nguoi_xu_ly',
    // 'nhiem_vu/giao/by_nguoi_xu_ly/0',
    // 'nhiem_vu/nhan/by_nguoi_xu_ly',
    // 'nhiem_vu/nhan/by_nguoi_xu_ly/0',
    // 'van_ban/den/nguoi_xu_ly',
    // 'van_ban/den/by_nguoi_xu_ly',
    // 'van_ban/di/nguoi_xu_ly',
    // 'van_ban/di/by_nguoi_xu_ly',
    // 'ds_khancap_tientrinh',
    // 'ds_van_ban',
    // 'van_ban_chi_tiet',
    // 'api/chi_tieu/chi_tieu_theo_linh_vuc',
    // 'api/chi_tieu/chi_tieu_chi_tiet/2/tien_trinh_thuc_hien',
    // 'api/chi_tieu/chi_tiet_chi_tieu',
    // 'ds_khan_cap',

    //'ds_khancap_tientrinh',
    //'ds_van_ban',
    //'van_ban_chi_tiet',
    //'api/chi_tieu/chi_tieu_theo_linh_vuc',
    //'mt_tien_trinh',
    //'api/chi_tieu/chi_tiet_chi_tieu',
    //'ds_khan_cap',
    'ds_thong_bao',
    // 'lichcongtac',
    // 'lichcongtac/0',
    'linhvucquanly',
    'muc_tieu_so_tai_chinh',
    'nhiem_vu_so_tai_chinh',
    // 'linh_vuc_quan_ly/qdpcnv',
    // 'linh_vuc_quan_ly/don_vi_phu_trach',
    // 'linh_vuc_quan_ly/su_kien_quan_trong',
    // 'linh_vuc_quan_ly/du_an_trong_diem',
    // 'linh_vuc_quan_ly/cv_cham_tiem_do',
    // 'lvql_chi_tiet_phan_cong',
    // 'linh_vuc_quan_ly/don_vi_phu_trach/ds_nhiem_vu_giao',
    'lvql_chi_tiet_du_an',
    'lvql_chi_tiet_cong_viec',
    // 'danLuan/getAllDanLuan',
    // 'master_ds_so',
    'master_ds_linh_vuc_bao_cao',
    // 'report/news',
    'connection/1',
    'connection/2',
    'connection/3'
];